config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get '/user', to:'users#index'
  get '/admin', to:'admins#index'
  get '/chofer', to:'chofers#index'
  devise_for :chofers
  devise_for :admins
  devise_for :users, controllers: { registrations: 'users/registrations' }

  resources :pasajes
  resources :viajes
  get '/listaViajes', to: 'viajes#listaViajes'

  get '/compraExpressViaje', to: 'viajes#compraExpressViaje', as: 'compraExpressViaje'
  put '/compraExpressViaje/:id', to: 'viajes#expressUpdate', as: 'expressUpdate'

  get '/choferViajes', to: 'chofers#choferViajes'
  put '/choferViajes/:id', to: 'chofers#editarEstado', as: 'editarEstado'
  get '/listaPasajeros/:id', to: 'chofers#choferPasajeros', as: 'listaPasajeros'
  get '/preguntasCovid/:id', to: 'chofers#preguntasCovid', as: 'preguntasCovid'
  put '/actualizarDatos/:id', to: 'chofers#actualizarDatos', as: 'actualizarDatos'

  get '/review/:id', to: 'viajes#review', as: 'edit_review'
  put '/review/:id', to: 'pasajes#updateReview',as:'updateReview'

  get '/registroExpress', to: 'users#registroExpress', as: 'registroExpress'
  post '/crearExpress', to: 'users#crearExpress', as: 'crearExpress'

  get '/insumos/:id', to: 'insumos#listaInsumos', as: 'listaInsumos'
  put '/compraInsumos/:id', to: 'insumos#compraInsumos', as: 'compraInsumos'
  put '/devolucionInsumo/:id', to: 'insumos#devolucionInsumo', as: 'devolucionInsumo'

  #get '/admin/crear_chofer', to: 'chofers#new'
  post '/admin/chofers', to: 'chofers#create'
  root 'main#default'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/chofer.rb
class Chofer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable #borre  :registerable, para que no se puedan registrar como choferes

  validates :nombre, presence:true
  validates :apellido, presence:true
  validates :dni, presence:true, uniqueness:true, length: {minimum: 8, maximum: 8}, numericality: true
  validates :telefono, presence:true, numericality: true
  validates :email, presence:true, uniqueness:true
  validates :password, presence:true
  validates :password_confirmation, presence:true
  
  #has_many :viajes


  def custom_label_method
    "#{self.nombre}"
  end

  rails_admin do
    exclude_fields :created_at, :updated_at, :remember_created_at, :reset_password_sent_at
  end

end

app/controllers/chofer/confirmations_controller.rb
# frozen_string_literal: true

class Chofer::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/chofer/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Chofer::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/chofer/passwords_controller.rb
# frozen_string_literal: true

class Chofer::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/chofer/registrations_controller.rb
# frozen_string_literal: true

class Chofer::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/chofer/sessions_controller.rb
# frozen_string_literal: true

class Chofer::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/chofer/unlocks_controller.rb
# frozen_string_literal: true

class Chofer::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/chofers_controller.rb
class ChofersController < ApplicationController
  before_action :authenticate_chofer! , except: [:new,:create]
  before_action :authenticate_admin!, only: [:new,:create]

  def index

  end

  def new
    @chofer = Chofer.new
  end

  def create
    #byebug
    @chofer = Chofer.new(params.require(:chofer).permit(:nombre, :password, :email, :apellido, :dni, :telefono))
    if @chofer.save
      redirect_to admin_path
    else
      render :new
    end
    return
  end

  def choferViajes
		@viaje = Viaje.where(chofer_id: current_chofer.id).order(:FechayHora)
  end

  def editarEstado
    @viaje = Viaje.find(params[:id])

    if (@viaje.pendiente?)
      @viaje.update(estado:"activo")
    else
      if (@viaje.activo?)
        @viaje.update(estado:"finalizado")
      end
    end
    redirect_to choferViajes_path
  end

  def choferPasajeros
    @viaje = Viaje.find(params[:id])
     userId = Pasaje.where(viaje_id:@viaje.id,estado:true).pluck(:user_id) #usuarios del viaje que no lo cancelaron
     @pasajeros = User.where(id:userId)
  end

  def preguntasCovid
    @pasaje = Pasaje.find(params[:id])
  end

  def actualizarDatos

    condicion = params[:perdida].to_i+params[:garganta].to_i+params[:respiratoria].to_i+params[:temperatura].to_i+params[:fiebre].to_i
    pasaje = Pasaje.find(params[:id])
    if (params[:temperatura] == "1") or  (condicion > 1)
      usuario = User.find(pasaje.user_id)
      usuario.update(covid: Date.today)      #acualizo la fecha del usuario para que no pueda comprar

      fechaLimite = Date.today + 15.days
      viajes = usuario.viajes.where(FechayHora: Date.today..fechaLimite)
      pasajes = Pasaje.where(user_id:usuario,viaje_id:viajes).where.not(id: pasaje)
      pasajes.update_all(estado:false)      #cancelo los demas viajes pendientes que tenia el usuario dentro de 15 dias

      pasaje.update(covid: true)            #aparece como rechazado en el viaje
      flash[:alert] = "Pasajero rechazado"

    else
      pasaje.update(covid: false)           #aparece como aceptado en el viaje
      flash[:notice] = "Pasajero aceptado"
    end
    redirect_to listaPasajeros_path(Viaje.find(pasaje.viaje_id))
  end

end

app/helpers/chofers_helper.rb
module ChofersHelper
end

app/views/chofers/_formChofer.html.erb
<%= form_for(@chofer, url: admin_chofers_path(@chofer), html: {method: "post"}) do |f| %>

<div class="field">
<%= f.label :nombre %>
<%= f.text_field :nombre %>
</div>

<div class="field">
<%= f.label :apellido %>
<%= f.text_field :apellido %>
</div>

<div class="field">
<%= f.label :email %>
<%= f.email_field :email %>
</div>

<div class="field">
    <%= f.label :password %>
    <%= f.password_field :password, autocomplete: "new-password" %>
</div>


<div class="field">
<%= f.label :dni %>
<%= f.text_field :dni %>
</div>

<div class="field">
<%= f.label :telefono %>
<%= f.number_field :telefono %>
</div>

<%= f.submit 'Guardar' %>
<% end %>

app/views/chofers/choferPasajeros.html.erb
<table class="table">
	<tr>
		<th> Nombre </th>
		<th> Apellido </th>
		<th> DNI </th>
		<th>Covid</th>
	</tr>

	<% @pasajeros.each do |pasajero| %>
        <tr>
            <td> 
                <%= pasajero.nombre%>
            </td>
            <td> 
                <%= pasajero.apellido%>
            </td>
            <td> 
                <%= pasajero.dni%>
            </td>
            <td>
            	<% pasaje = Pasaje.where(viaje_id:@viaje, user_id:pasajero.id).first %>
            	<% if pasaje.covid.nil? %>

            		<%= link_to 'Preguntas Covid', preguntasCovid_path(pasaje) , class: 'btn btn-warning' %>

            		<% elsif pasaje.covid %>
            				<p class="btn btn-danger" > Rechazado </p>
							
                   		<% else %>
                        	<p class="btn btn-success"> Aceptado </p>
                <% end %>
            </td>
		</tr>
	<% end %>

	<% if @pasajeros.size == 0 %>
		<tr> <td colspan="3"> No hay pasajeros </td> </tr>
	<% end %>

</table>

app/views/chofers/choferViajes.html.erb
<table class="table">
	<tr>
		<th> Origen </th>
		<th> Destino </th>
		<th> Combi </th>
		<th> Fecha </th>
		<th>Estado del viaje </th>
		<th> Listado de Pasajeros </th>
	</tr>

	<% @viaje.each do |viaje| %>
		<tr>
			<td> <%= Lugar.find(Camino.find(viaje.camino_id).origen_id).ciudad %> <%= Lugar.find(Camino.find(viaje.camino_id).origen_id).provincia %> </td>
			<td> <%= Lugar.find(Camino.find(viaje.camino_id).destino_id).ciudad %> <%= Lugar.find(Camino.find(viaje.camino_id).destino_id).provincia   %> </td>
            <td> <% if Combi.find(viaje.combi_id).super_comoda %>
                         Super Comoda
                    <% else %>
                         Normal
                    <% end %>
            </td>
			<td> <%= viaje.FechayHora.to_formatted_s(:db) %> </td>
			<td>
				<%if viaje.estado == 'pendiente' %>
					<%= link_to viaje.estado,editarEstado_path(viaje), method: :put, class: 'btn btn-warning' %>
				<%elsif viaje.estado == 'activo' %>
					<%= link_to viaje.estado,editarEstado_path(viaje), method: :put, class: 'btn btn-primary' %>
				<%else%>
					<%= link_to viaje.estado,editarEstado_path(viaje), method: :put, class: 'btn btn-danger' %>
				<%end%>
			</td>
			<td>
				<%if viaje.estado != 'finalizado' %>
					<%= link_to "Lista de pasajeros",listaPasajeros_path(viaje), class: 'btn btn-success' %>
				<%end%>
			</td>
		</tr>
	<% end %>

	<% if @viaje.size == 0 %>
		<tr> <td colspan="3"> No hay Viajes </td> </tr>
	<% end %>

</table>

app/views/chofers/index.html.erb
<div class="container-md">
<%= link_to 'Listado de viajes ' , choferViajes_path, class: 'btn btn-primary' %>
</div>

app/views/chofers/new.html.erb
<h1> Nuevo Chofer </h1>

<%= render 'formChofer' %>

<%= link_to 'Volver', root_path %>

app/views/chofers/preguntasCovid.html.erb
<%= form_with url: actualizarDatos_path(@pasaje), method: :put %>

<h2>En la ultima semana: </h2>

<ul class="list-group list-group-flush">
  <li class="list-group-item">
  	<h3>Tuvo fiebre?</h3>
  	<%= radio_button_tag(:fiebre, 1) %>
	<%= label_tag("SI") %>
	<%= radio_button_tag(:fiebre, 0, :require => true) %>
	<%= label_tag( "NO") %>
  </li>
  <li class="list-group-item">
  	<h3>Tuvo pérdida de gusto y/o olfato?</h3>
  	<%= radio_button_tag(:perdida, 1) %>
	<%= label_tag("SI") %>
	<%= radio_button_tag(:perdida, 0, :require => true) %>
	<%= label_tag( "NO") %>
  </li>
  <li class="list-group-item">
  	<h3>Tuvo dolor de garganta?</h3>
  	<%= radio_button_tag(:garganta, 1) %>
	<%= label_tag("SI") %>
	<%= radio_button_tag(:garganta, 0, :require => true) %>
	<%= label_tag( "NO") %>
  </li>
  <li class="list-group-item">
  	<h3>Tuvo dificultad respiratoria?</h3>
  	<%= radio_button_tag(:respiratoria, 1) %>
	<%= label_tag("SI") %>
	<%= radio_button_tag(:respiratoria, 0, :require => true) %>
	<%= label_tag( "NO") %>
  </li>
  <li class="list-group-item">
  	<h3>Su temperatura es:</h3>
  	<%= radio_button_tag(:temperatura, 1) %>
	<%= label_tag("Mayor que 37°") %>
	<br>
	<%= radio_button_tag(:temperatura, 0, :require => true) %>
	<%= label_tag( "Menor que 37°") %>
  </li>
</ul>

 <%= submit_tag("Enviar") %>