config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get '/user', to:'users#index'
  get '/admin', to:'admins#index'
  get '/chofer', to:'chofers#index'
  devise_for :chofers
  devise_for :admins
  devise_for :users, controllers: { registrations: 'users/registrations' }

  resources :pasajes
  resources :viajes
  get '/listaViajes', to: 'viajes#listaViajes'

  get '/compraExpressViaje', to: 'viajes#compraExpressViaje', as: 'compraExpressViaje'
  put '/compraExpressViaje/:id', to: 'viajes#expressUpdate', as: 'expressUpdate'

  get '/choferViajes', to: 'chofers#choferViajes'
  put '/choferViajes/:id', to: 'chofers#editarEstado', as: 'editarEstado'
  get '/listaPasajeros/:id', to: 'chofers#choferPasajeros', as: 'listaPasajeros'
  get '/preguntasCovid/:id', to: 'chofers#preguntasCovid', as: 'preguntasCovid'
  put '/actualizarDatos/:id', to: 'chofers#actualizarDatos', as: 'actualizarDatos'

  get '/review/:id', to: 'viajes#review', as: 'edit_review'
  put '/review/:id', to: 'pasajes#updateReview',as:'updateReview'

  get '/registroExpress', to: 'users#registroExpress', as: 'registroExpress'
  post '/crearExpress', to: 'users#crearExpress', as: 'crearExpress'

  get '/insumos/:id', to: 'insumos#listaInsumos', as: 'listaInsumos'
  put '/compraInsumos/:id', to: 'insumos#compraInsumos', as: 'compraInsumos'
  put '/devolucionInsumo/:id', to: 'insumos#devolucionInsumo', as: 'devolucionInsumo'

  #get '/admin/crear_chofer', to: 'chofers#new'
  post '/admin/chofers', to: 'chofers#create'
  root 'main#default'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/viaje.rb
class Viaje < ApplicationRecord
    enum estado: [:pendiente,:activo,:finalizado]

    #has_and_belongs_to_many :users
    has_many :pasajes
    has_many :users, :through => :pasajes
    belongs_to :combi
    belongs_to :chofer
    belongs_to :camino

    validates :chofer_id, uniqueness: { scope: [:camino_id, :FechayHora, :combi_id] }#, message: "must be given please"

    def custom_label_method
		"Viaje #{self.id}"
    end


    def formatoViaje
        "#{Lugar.find(Camino.find(self.camino_id).origen_id).ciudad}/#{Lugar.find(Camino.find(self.camino_id).origen_id).provincia} - #{Lugar.find(Camino.find(self.camino_id).destino_id).ciudad}/#{Lugar.find(Camino.find(self.camino_id).destino_id).provincia} - #{self.FechayHora.to_formatted_s(:db)}" # Origen Destino Fecha
    end

    rails_admin do
        exclude_fields :created_at, :updated_at, :users, :pasajes
    end

end

app/controllers/viajes_controller.rb
class ViajesController < ApplicationController

	before_action :authenticate_user!
	def index
		viajeValido = Viaje.all.where(estado: "pendiente")
		@viajeSolo = viajeValido.first
		if (@viajeSolo.nil?)
			flash[:alert] = "No existen viajes para comprar"
			redirect_to user_path
		end
    	@viaje = viajeValido.all
  end

	def update
		@viaje=Viaje.find(params[:viaje])
		pasaje = Pasaje.where(viaje_id:@viaje.id, user_id:current_user.id)
		espacio_disponible = Pasaje.where(viaje_id:@viaje.id, estado:true).count


	    	if ( espacio_disponible < Combi.find(@viaje.combi_id).capacidad) #espacio disponible
				if(current_user.FechaExpiracion > Date.today)#tarjeta cancelada
					if((current_user.covid.nil?) or (current_user.covid + 15.days) < @viaje.FechayHora.to_date) #covid
	    				if (pasaje.first.nil?) #no compro alguna vez este viaje
	    					@viaje.users << User.find(current_user.id)
							flash[:notice] = "La compra se realizo con exito"
						else
							if (pasaje.first.estado)  #si el viaje esta pendiente o cancelado
	    						flash[:alert] = "Ya compraste este viaje"
	    					else
	    						pasaje.first.estado = true
	    						pasaje.first.save
	    						flash[:notice] = "La compra se realizo con exito"
	    					end
	    				end
					else
						flash[:alert] = "No puede comprar por covid"
					end
	    		else
	    			flash[:alert] = "Su tarjeta ha expirado"
	    		end
	    	else
	    		flash[:alert] = "Ya no quedan espacios disponibles"
	    	end
	    redirect_to viajes_path
	end

	def expressUpdate
		@viaje=Viaje.find(params[:viaje])
		pasaje = Pasaje.where(viaje_id:@viaje.id, user_id:current_user.id)
		espacio_disponible = Pasaje.where(viaje_id:@viaje.id, estado:true).count


	    	if ( espacio_disponible < Combi.find(@viaje.combi_id).capacidad) #espacio disponible
					if((current_user.covid.nil?) or (current_user.covid + 15.days) < @viaje.FechayHora.to_date) #covid
	    				if (pasaje.first.nil?) #no compro alguna vez este viaje
	    					@viaje.users << User.find(current_user.id)
							flash[:notice] = "La compra se realizo con exito"
						else
							if (pasaje.first.estado)  #si el viaje esta pendiente o cancelado
	    						flash[:alert] = "Ya compraste este viaje"
	    					else
	    						pasaje.first.estado = true
	    						pasaje.first.save
	    						flash[:notice] = "La compra se realizo con exito"
	    					end
	    				end
					else
						flash[:alert] = "No puede comprar por covid"
					end
	    	else
	    		flash[:alert] = "Ya no quedan espacios disponibles"
	    	end
	    redirect_to compraExpressViaje_path
	end

	def compraExpressViaje
		viajeValido = Viaje.all.where(estado: "activo")
		@viajeSolo = viajeValido.first
		if (@viajeSolo.nil?)
			flash[:alert] = "No existen viajes para comprar"
			redirect_to user_path
		end
    	@viaje = viajeValido.all
  end

	def review
    @pasaje=Pasaje.find(params[:id])
		if not(@pasaje.estado)
			redirect_to listaViajes_path
		end
	end

	def listaViajes
		@viaje = current_user.viajes.order(:FechayHora)
	end
end

app/helpers/viajes_helper.rb
module ViajesHelper
end

app/views/viajes/_formBuscar.html.erb
<%= form_tag( viajes_path, method: :get) do %>
  <%= text_field_tag(:search, params[:search]) %>
  <%= submit_tag("Search") %>
<% end %>

app/views/viajes/compraExpressViaje.html.erb
<div class="container-md">
<h3>Buscar viaje</h3>

<%= form_for @viajeSolo, url: expressUpdate_path(@viajeSolo), method: :put do |f| %>
 <h5>Formato: Origen - Destino - Fecha - Hora </h5>
 <h6>Ciudad / Provincia </h6>

   <select name="viaje" class="js-example-basic-single">
     <% @viaje.each do |viaje| %>
       <option value="<%= viaje.id %>"><%= viaje.formatoViaje %></option>
     <% end %>
   </select>


 <%= f.submit 'Comprar', class: "btn btn-primary" %>
<% end %>
</div>

app/views/viajes/index.html.erb
<div class="container-md">
<h3>Buscar viaje</h3>



<%= form_for @viajeSolo do |f| %>
 <h5>Formato: Origen - Destino - Fecha - Hora </h5>
 <h6>Ciudad / Provincia </h6>

   <select name="viaje" class="js-example-basic-single">
     <% @viaje.each do |viaje| %>
       <option value="<%= viaje.id %>"><%= viaje.formatoViaje %></option>
     <% end %>
   </select>


 <%= f.submit 'Comprar', class: "btn btn-primary" %>
<% end %>
</div>

app/views/viajes/listaViajes.html.erb
<table class="table">
	<tr>
		<th> Origen </th>
		<th> Destino </th>
		<th> Combi </th>
		<th> Fecha </th>
		<th> Estado del pasaje </th>
		<th>Estado del viaje </th>
		<th> Insumos </th>
	</tr>

	<% @viaje.each do |viaje| %>
		<tr>
			<td> <%= Lugar.find(Camino.find(viaje.camino_id).origen_id).ciudad %> <%= Lugar.find(Camino.find(viaje.camino_id).origen_id).provincia %> </td>
			<td> <%= Lugar.find(Camino.find(viaje.camino_id).destino_id).ciudad %> <%= Lugar.find(Camino.find(viaje.camino_id).destino_id).provincia   %> </td>
            <td> <% if Combi.find(viaje.combi_id).super_comoda %>
                         Super Comoda
                    <% else %>
                         Normal
                    <% end %>
            </td>
			<td> 
				<%= viaje.FechayHora.to_formatted_s(:db) %> 
			</td>
			<td> <% if Pasaje.where(viaje_id:viaje.id, user_id:current_user.id).first.estado and !(Pasaje.where(viaje_id:viaje.id, user_id:current_user.id).first.covid)%>
						Activo
                    <% else %>
                        Cancelado
                    <% end %>
			</td>
			<td>
        		<%= viaje.estado %>
			</td>

			<td>
				
				<% if Pasaje.where(viaje_id:viaje.id, user_id:current_user.id).first.estado and !(Pasaje.where(viaje_id:viaje.id, user_id:current_user.id).first.covid)%>
					<% if  viaje.pendiente?%>
		  				<%= link_to 'Insumos' , listaInsumos_path(Pasaje.where(viaje_id:viaje.id, user_id:current_user.id).first) ,  class: 'btn btn-success' %>
		  			<% end %>
				<% end %>
			</td>

			<td>
				<% if Pasaje.where(viaje_id:viaje.id, user_id:current_user.id).first.estado and !(Pasaje.where(viaje_id:viaje.id, user_id:current_user.id).first.covid)%>
		  		<% if  viaje.finalizado?%>
		  			<%= link_to 'Agregar/Editar Reseña' , edit_review_path(Pasaje.where(viaje_id:viaje.id, user_id:current_user.id).first) ,  class: 'btn btn-success' %>
		  		<% end %>
					<% if  viaje.pendiente?%>
		  			<%= link_to 'Cancelar' , pasaje_path(Pasaje.where(viaje_id:viaje.id, user_id:current_user.id).first.id), method: :put , :data => {confirm: 'Esta seguro que quiere cancelar el viaje? si faltan menos de 48hs solo se reintegrara el 50%'}, class: 'btn btn-primary' %>
		  			<% end %>
				<% end %>
				<%if Pasaje.where(viaje_id:viaje.id, user_id:current_user.id).first.covid %>
					<h5 class="badge bg-info text-wrap" style="width: 6rem;">No pudo viajar por Covid</h5>
				<%end%>
			</td>
		</tr>
	<% end %>

	<% if @viaje.size == 0 %>
		<tr> <td colspan="3"> No hay Viajes </td> </tr>
	<% end %>

</table>

app/views/viajes/review.html.erb
<%= form_for @pasaje, url: updateReview_path(@pasaje), method: :put do |f| %>

<div class="container-md">
 <%= f.label 'Deje un comentario y un puntaje: ' %><br/>
 <%= f.text_area :comentario , class:'cien' %>

 <input type="text" name="accion" value="editado" hidden />

<div id="contenedorStars">
 <div class="rating">
   <input type="radio" name="rating" value="5" id="5" <%= if (@pasaje.puntaje==5) then "checked" end %>>
   <label for="5">☆</label>
   <input type="radio" name="rating" value="4" id="4" <%= if (@pasaje.puntaje==4) then "checked" end %>>
   <label for="4">☆</label>
   <input type="radio" name="rating" value="3" id="3" <%= if (@pasaje.puntaje==3) then "checked" end %>>
   <label for="3">☆</label>
   <input type="radio" name="rating" value="2" id="2" <%= if (@pasaje.puntaje==2) then "checked" end %>>
   <label for="2">☆</label>
   <input type="radio" name="rating" value="1" id="1" <%= if (@pasaje.puntaje==1) then  "checked" end %>>
   <label for="1">☆</label>
 </div>
 <div>


 <%= f.submit 'Enviar' ,class: 'btn btn-success' %>
 <%= link_to 'Cancelar', listaViajes_path, class: 'btn btn-light' %>
 </div>
<% end %>
<br/>
<% if not(@pasaje.puntaje.nil?) and @pasaje.puntaje > 0 %>
  <%= link_to 'Eliminar Reseña' , updateReview_path(:pasaje => {:comentario => ""},:accion => "eliminar",:format => @pasaje.id, :rating => @pasaje.puntaje), pasaje: @pasaje,method: :put , class: 'btn btn-danger' %>
<% end %>