config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get '/user', to:'users#index'
  get '/admin', to:'admins#index'
  get '/chofer', to:'chofers#index'
  devise_for :chofers
  devise_for :admins
  devise_for :users, controllers: { registrations: 'users/registrations' }

  resources :pasajes
  resources :viajes
  get '/listaViajes', to: 'viajes#listaViajes'

  get '/compraExpressViaje', to: 'viajes#compraExpressViaje', as: 'compraExpressViaje'
  put '/compraExpressViaje/:id', to: 'viajes#expressUpdate', as: 'expressUpdate'

  get '/choferViajes', to: 'chofers#choferViajes'
  put '/choferViajes/:id', to: 'chofers#editarEstado', as: 'editarEstado'
  get '/listaPasajeros/:id', to: 'chofers#choferPasajeros', as: 'listaPasajeros'
  get '/preguntasCovid/:id', to: 'chofers#preguntasCovid', as: 'preguntasCovid'
  put '/actualizarDatos/:id', to: 'chofers#actualizarDatos', as: 'actualizarDatos'

  get '/review/:id', to: 'viajes#review', as: 'edit_review'
  put '/review/:id', to: 'pasajes#updateReview',as:'updateReview'

  get '/registroExpress', to: 'users#registroExpress', as: 'registroExpress'
  post '/crearExpress', to: 'users#crearExpress', as: 'crearExpress'

  get '/insumos/:id', to: 'insumos#listaInsumos', as: 'listaInsumos'
  put '/compraInsumos/:id', to: 'insumos#compraInsumos', as: 'compraInsumos'
  put '/devolucionInsumo/:id', to: 'insumos#devolucionInsumo', as: 'devolucionInsumo'

  #get '/admin/crear_chofer', to: 'chofers#new'
  post '/admin/chofers', to: 'chofers#create'
  root 'main#default'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :recoverable, 
         :rememberable, :validatable #borre  :registerable, para que no se puedan registrar como administradores

  validates :email, presence:true, uniqueness:true
  validates :password, presence:true
  validates :password_confirmation, presence:true
  rails_admin do
    exclude_fields :created_at, :updated_at, :remember_created_at, :reset_password_sent_at
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/camino.rb
class ValidarLugar < ActiveModel::Validator
	def validate(aux)
		if aux[:origen_id].eql? aux[:destino_id]
			aux.errors.add :base, "El origen y el destino no pueden ser los mismos"
		end
	end
end

class Camino < ApplicationRecord
	validates :camino, presence:true
	#has_many :viajes
	
	belongs_to :origen, class_name: 'Lugar'
	belongs_to :destino, class_name: 'Lugar'
	
	validates_with ValidarLugar,field: [:origen, :destino]
	
	def custom_label_method
		"#{self.camino}"
	end

    rails_admin do
        exclude_fields :created_at, :updated_at
    end

end

app/models/carrito.rb
class Carrito < ApplicationRecord
  belongs_to :pasaje
  belongs_to :insumo
end

app/models/chofer.rb
class Chofer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable #borre  :registerable, para que no se puedan registrar como choferes

  validates :nombre, presence:true
  validates :apellido, presence:true
  validates :dni, presence:true, uniqueness:true, length: {minimum: 8, maximum: 8}, numericality: true
  validates :telefono, presence:true, numericality: true
  validates :email, presence:true, uniqueness:true
  validates :password, presence:true
  validates :password_confirmation, presence:true
  
  #has_many :viajes


  def custom_label_method
    "#{self.nombre}"
  end

  rails_admin do
    exclude_fields :created_at, :updated_at, :remember_created_at, :reset_password_sent_at
  end

end

app/models/combi.rb
class Combi < ApplicationRecord
  validates :patente, presence:true, uniqueness:true
  validates :capacidad, presence:true, numericality: true
  validates :modelo, presence:true
  #has_many :viajes


  def custom_label_method
		"#{self.patente}"
	end

    rails_admin do
        exclude_fields :created_at, :updated_at
    end
    
end

app/models/insumo.rb
class Insumo < ApplicationRecord

  has_many :carritos
  has_many :pasajes, :through => :carritos

  validates :precio, presence: true
  validates :nombre, presence:true , uniqueness:true

    def custom_label_method
		"#{self.nombre}"
	 end
	
    rails_admin do
        exclude_fields :created_at, :updated_at, :carritos, :pasajes
    end
end

app/models/lugar.rb
#class ValidarLugar < ActiveModel::Validator
#	def validate(aux)
#		if aux[:origen].eql? aux[:destino]
#			aux.errors.add :base, "El origne y el destino no pueden ser los mismos"
#		end
#	end
#end


class Lugar < ApplicationRecord
	validates :ciudad, presence: true#, uniqueness:true
	validates :provincia, presence: true
	#validates_with ValidarLugar,field: [:origen, :destino]
	validates :ciudad, uniqueness: { scope:  :provincia }
	#validates_uniqueness_of :car_model_name, :scope => [:brand_id, :fuel_type_id]

	def custom_label_method
		"#{self.ciudad}"
	end

    rails_admin do
        exclude_fields :created_at, :updated_at
    end
end

app/models/pasaje.rb
class Pasaje < ApplicationRecord
  belongs_to :viaje
  belongs_to :user

  has_many :carritos
  has_many :insumos, :through => :carritos
end

app/models/user.rb
class ValidarTarjeta < ActiveModel::Validator
  def validate(aux)
    if aux[:FechaExpiracion] != nil
      if aux[:FechaExpiracion] < Date.today
        aux.errors.add :base, "La tarjeta expiro"
      end
    end
  end
end


class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :email, presence:true, uniqueness:true
  validates :password, presence:true, on: :create
  validates :password_confirmation, presence:true, on: :create
  validates_with ValidarTarjeta,field: [:FechaExpiracion], on: :create
  validates :nombre, presence:true
  validates :apellido, presence:true
  validates :dni, presence:true, uniqueness:true, length: {minimum: 8, maximum: 8}, numericality: true
  validates :tarjeta, presence:true, length: {minimum: 16, maximum: 16}
  validates :FechaExpiracion, presence:true
  

  #has_and_belongs_to_many :viaje
  has_many :pasajes
  has_many :viajes, :through => :pasajes

  def custom_label_method
		"#{self.nombre}"
	end

  rails_admin do
    exclude_fields :created_at, :updated_at, :remember_created_at, :reset_password_sent_at
  end


end

app/models/viaje.rb
class Viaje < ApplicationRecord
    enum estado: [:pendiente,:activo,:finalizado]

    #has_and_belongs_to_many :users
    has_many :pasajes
    has_many :users, :through => :pasajes
    belongs_to :combi
    belongs_to :chofer
    belongs_to :camino

    validates :chofer_id, uniqueness: { scope: [:camino_id, :FechayHora, :combi_id] }#, message: "must be given please"

    def custom_label_method
		"Viaje #{self.id}"
    end


    def formatoViaje
        "#{Lugar.find(Camino.find(self.camino_id).origen_id).ciudad}/#{Lugar.find(Camino.find(self.camino_id).origen_id).provincia} - #{Lugar.find(Camino.find(self.camino_id).destino_id).ciudad}/#{Lugar.find(Camino.find(self.camino_id).destino_id).provincia} - #{self.FechayHora.to_formatted_s(:db)}" # Origen Destino Fecha
    end

    rails_admin do
        exclude_fields :created_at, :updated_at, :users, :pasajes
    end

end

app/controllers/main_controller.rb
class MainController < ApplicationController
  before_action :redireccionar
  
  def redireccionar
      if user_signed_in?
        redirect_to user_path
      end
      if chofer_signed_in?
        redirect_to chofer_path
      end
      if admin_signed_in?
        redirect_to  rails_admin_path
      end
  end

  def default
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chofers_helper.rb
module ChofersHelper
end

app/helpers/insumos_helper.rb
module InsumosHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/pasajes_helper.rb
module PasajesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/viajes_helper.rb
module ViajesHelper
end

app/views/admins/index.html.erb
<h1>Admins#index</h1>
<p>Find me in app/views/admins/index.html.erb</p>

app/views/layouts/_header.html.erb
<header>
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">


          <%= link_to root_path, class: 'navbar-brand' do %>
            <%= image_tag "combi19.png", title: "Logo", class: "logo w-25 pr-3" %>
            Combi19
          <% end %>

          <% if not(user_signed_in?) and not(chofer_signed_in?) and not(admin_signed_in?) %>
            <%= link_to "Iniciar sesion como pasajero", new_user_session_path, class: 'btn btn-primary' %>
            <%= link_to "Iniciar sesion como chofer", new_chofer_session_path, class: 'btn btn-primary' %>
            <%= link_to "Registrarse", new_user_registration_path, class: 'btn btn-secondary' %>
            <%= link_to "Registrarse express", registroExpress_path, class: 'btn btn-secondary' %>
          <%else%>
            <%= link_to "Desloguearse",destroy_user_session_path, method: :delete %>
          <% end %>
        <div class="collapse navbar-collapse">

        </div><!--/.nav-collapse -->
      </div>

    </div>
  </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Combi19</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/css/select2.min.css" rel="stylesheet" />

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
  </head>

  <body>

    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <%= render 'layouts/header' %>

    <%= yield %>

    <%= javascript_pack_tag 'custom' %>

    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/js/select2.min.js"></script>
  </body>
</html>